[package]
name = "td"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
dirs = "6.0.0"
owo-colors = "4.2.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
